steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/thecommons-lab-vishravars/primer-repo/spark-assembly-lab:latest', '-f', 'Dockerfile.prod', '.']
images:
- 'us-central1-docker.pkg.dev/thecommons-lab-vishravars/primer-repo/spark-assembly-lab:latest'
